feat: project sprint 15
Popsinator/java-shareit pull request #3
Opened 2022-12-04 22:41 UTC by Popsinator

2022-12-05 17:43 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-05 17:43 UTC, FanaticFiz commented on index.html
> +<!DOCTYPE html>
Что это за файлы?
Может я чегот не знаю ))

Но пока вердикт - удалить css, img и js

2022-12-05 17:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>      private Item item;
Делай отступы между полями, при большом кол-ве аннотаций всё сливается!

2022-12-05 17:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Page<Booking> findAll(Pageable pageable);
Вот эти методы

```
    Booking save(Booking booking);
    List<Booking> findAll();
    Page<Booking> findAll(Pageable pageable);
```

 есть в классах от которые мы расширяем т.е. в JpaRepository
 Поэтому они тут совершенно не нужны, их можно удалить и всё будет работать! ))

2022-12-05 17:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    Collection<BookingDto> getAllBookings(int userId, String state, String from, String size);
Нужно еще в контроллере подготовить PageRequest из `from, size`

Это будет подразумевать и их валидацию, которая сейчас в сервисе!
Валидировать входные параметры это прямая обязанность контроллеров.

Поэтому проверили и валидный PageRequest передаём в сервис.

2022-12-05 17:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            temp = bookingRepository.findAll().stream().filter(x -> x.getBooker().getId() == userId).collect(Collectors.toList());
Плохо брать из БД ВСЕ записи, чтобы потом кодом что-то там фильтровать!
БД с этим справиться гораздо эффективнее!
Записей в БД бывает десятки миллионов, у тебя даже память может закончиться пытаясь выгребать это всё...

2022-12-05 17:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/EmptyDescriptionReuestException.java
> +public class EmptyDescriptionReuestException extends RuntimeException {
Зачем же так!
Как много работы проделано... !
Ну надо же быть настоящим - ЛЕНИВЫМ программистом!!!

Зачем же созданы все эти ексепшены?
Невозможно создать по ексепшену на каждое поле!

Должен быть ОДИН ексепшн с названием: `BadRequestException` вместо всех ексепшенов связанных с неправильными полями...

Какое бы поле не было неправильным мы кидаем этот один ексепшн с пояснением что не так.

2022-12-05 17:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse handleInvalidParamsPaginationInRequestException(final InvalidParamsPaginationException exception) {
Соответственно и тут всё по удалять и оставить только общие ексепшены по одному для каждого HttpStatus кода, которые мы используем.

Например для HttpStatus.NOT_FOUND должен быть: `NotFoundException`

2022-12-05 17:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    @Column(name = "request_id")
Нет полного описания полей, в соответствии с базой данных, например в БД поле
`description` имеет длину 512, значит и тут это должно быть указано!

2022-12-05 17:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private LastBooking lastBooking;
Не понимаю смысла в lastBooking и nextBooking...
Зачем они, зачем мы записываем их в сущность Item?

2022-12-05 17:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
> +    @Column(name = "description", nullable = false)
- Описать поля согласно БД
- добавить отступы между полями

2022-12-05 17:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/requests/ItemRequestReporistory.java
> +    ItemRequest save(ItemRequest request);
Во всех репозиториях описаны методы которые описывать не нужно было... см. предыдущий коммент, проследи за всеми репозиториями.

2022-12-05 17:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/requests/ItemRequestService.java
> +    List<ItemRequest> getRequest(int userId);
`getRequest` -> `getRequests` мы же список возвращаем...

2022-12-05 17:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>          for (User value : repository.findAll()) {
Этот метод должен перестать существовать! 
Опять же вытаскиваешь ВСЁ чтобы найти один...
Тебе в репозитории нужны два метода с сигнатурами: 

`Optional<User> findById(int id);` - для того чтобы доставать по id
`boolean existsById(int id);` - для того чтобы проверять по id

2022-12-05 19:22 UTC, Popsinator commented on index.html
> +<!DOCTYPE html>
Удалил.

2022-12-05 19:29 UTC, Popsinator commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>      private Item item;
Сделал.

2022-12-05 19:48 UTC, Popsinator commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Page<Booking> findAll(Pageable pageable);
Понял, спасибо большое, совсем об этом не подумал. Исправлю во всех репозиториях.

2022-12-05 20:19 UTC, Popsinator commented on index.html
> +<!DOCTYPE html>
Это я мудрил с запуском тестов на покрытие, эти папки на создавались, и потом забыл их удалить.

2022-12-05 20:31 UTC, Popsinator commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    Collection<BookingDto> getAllBookings(int userId, String state, String from, String size);
Чтобы не сильно переделывать логику я в контроллер добавил проверку на null значения и в этом случае передаю пустые строки в сервис.
А в сервисе тогда буду проверять на пустые строки, так как в постмане есть тесты на запрос без пагинации, поэтому мне это нужно, чтобы разделить эти случаи.
В сервис теперь не будут идти null значения.

2022-12-05 21:54 UTC, Popsinator commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            temp = bookingRepository.findAll().stream().filter(x -> x.getBooker().getId() == userId).collect(Collectors.toList());
Сделал, спасибо.

2022-12-05 22:06 UTC, Popsinator commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private LastBooking lastBooking;
Идея была в предыдущем спринте у меня такой:
В постман тесте у item проверялись lastBooking и nextBooking соответсвенно, я их добавил в item, сделал их @Transient чтобы не писать в базу. Посмотрел в тесте какие поля у них должны быть и создал такой Booking с необходимыми полями, и отправлял на фронт.

По этому пункту правок не делал.

2022-12-05 22:07 UTC, Popsinator commented on src/main/java/ru/practicum/shareit/requests/ItemRequestReporistory.java
> +    ItemRequest save(ItemRequest request);
Сделал.

2022-12-05 22:11 UTC, Popsinator commented on src/main/java/ru/practicum/shareit/requests/ItemRequestService.java
> +    List<ItemRequest> getRequest(int userId);
Сделал.

2022-12-05 23:28 UTC, Popsinator commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>          for (User value : repository.findAll()) {
Принцип я понял, для boolean existsById(int id) я все сделал.
А для Optional<User> findById(int id) есть же findUserByIdEquals.
А тот кусочек кода для которого этот комментарий, я вообще удалил в итоге.

2022-12-05 23:32 UTC, Popsinator commented on src/main/java/ru/practicum/shareit/exception/EmptyDescriptionReuestException.java
> +public class EmptyDescriptionReuestException extends RuntimeException {
Логику я понял.
Так как я так делал с 13 спринта, можно я к следующему спринту сделаю красиво, у меня будет получается три ексепшена, и в handlere три обработчика для них.
И в тесты и в коде перелопачу тогда все выбросы, переделаю пояснения, и к концу следующего спринта сделаю уже красиво. Прошу так, потому что очень хочу уложиться в сроки со следующим спринтом.

2022-12-05 23:34 UTC, Popsinator commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse handleInvalidParamsPaginationInRequestException(final InvalidParamsPaginationException exception) {
Да, я понял, сделаю. Можно пожалуйста только к следующему спринту, очень хочется по срокам уложиться.

2022-12-05 23:42 UTC, Popsinator commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    @Column(name = "request_id")
Сделал.

2022-12-05 23:43 UTC, Popsinator commented on src/main/java/ru/practicum/shareit/requests/ItemRequest.java
> +    @Column(name = "description", nullable = false)
Поля добавил, отступы тоже.

2022-12-06 03:31 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>          for (User value : repository.findAll()) {
принято

2022-12-06 03:32 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/EmptyDescriptionReuestException.java
> +public class EmptyDescriptionReuestException extends RuntimeException {
принимается

2022-12-06 16:54 UTC, FanaticFiz approved these changes

2022-12-06 16:54 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +
между аннотациями отступы не нужны, только между полями

2022-12-27 09:05 UTC, merged