Add docker
Popsinator/java-shareit pull request #4
Opened 2022-12-19 21:41 UTC by Popsinator

Тестовая заливка проекта 16 спринта.

2022-12-20 19:48 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-20 19:48 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
Эти классы исключений в том сервисе уместны и видно что используются, а в этом сервисе?

2022-12-20 19:48 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/item/Item.java
> +public class Item {
Меня сбивает с толку название `Item` как будто это модель сохраняемая в базу а не dto... 
А в gateway у нас должны быть dto которые должны проверяться аннотациями валидаций. 
А те dto которые я встречаю они не содержат валидации.

2022-12-20 19:48 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/user/User.java
> +public class User {
Ну вот еще раз... это `dto` ?  Почему не называется так? ))
Если это UserDto то почему нет валидации совсем?

2022-12-20 19:48 UTC, FanaticFiz commented on gateway/src/main/resources/application.properties
> +#logging.level.httpclient.wire=DEBUG
мусор не забываем удалять

2022-12-20 19:48 UTC, FanaticFiz commented on index.html
> +<!DOCTYPE html>
назначение этого файла мне не понятно!? ))

2022-12-20 19:48 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/item/ItemService.java
> +    //Collection<Item> findAllItem();
Не забываем это удалять.

Пользуйся более общепринятым интерфейсом List вместо Collection

2022-12-20 19:48 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            throw new InternalServerErrorException("Отсутствует заголовок 'X-Sharer-User-Id'");
Проверяй это в контроллере это же его ответственность эти заголовки...

2022-12-20 19:48 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +    private final ItemRequestReporistory requestReporistory;
Опечаталась!

2022-12-20 19:48 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +        List<ItemRequest> requestList = requestReporistory.findAllByRequester_IdNot(userId, PageRequest.of(start, size, Sort.by("created"))).stream().collect(Collectors.toList());
Очень длинная строка, в которой не разберешься!
Комбинируя методы через точку переноси каждую новую операцию на новую строку.

Выноси некоторые вещи в переменные если они не дают написать компактную строку.

2022-12-20 19:48 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +            throw new BadRequestException("Некорректные параметры пагинации.");
Тоже можно было бы проверять в контроллере...

2022-12-20 19:48 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>          return repository.findUserByIdEquals(userId);
этот метод `findUserByIdEquals` может возвращать Optional<User> и тогда код может выглядеть так.

```
    @Override
    public User getUser(int userId) {
        return repository.findUserByIdEquals(userId)
                         .orElseThrow(() -> new NotFoundException(String.format(
                                 "Пользователь с данным id %s не зарегистрирован.", userId)));
    }
```

Думаю тебе стоит освоить Optional ! ))

2022-12-21 06:02 UTC, Popsinator commented on gateway/src/main/resources/application.properties
> +#logging.level.httpclient.wire=DEBUG
Сделал. Забыл про него. Спасибо.

2022-12-21 06:05 UTC, Popsinator commented on index.html
> +<!DOCTYPE html>
Файл убрал.

2022-12-21 06:07 UTC, Popsinator commented on server/src/main/java/ru/practicum/shareit/item/ItemService.java
> +    //Collection<Item> findAllItem();
Да, тоже забыл удалить, просмотрел, спасибо.

2022-12-21 06:08 UTC, Popsinator commented on server/src/main/java/ru/practicum/shareit/item/ItemService.java
> +    //Collection<Item> findAllItem();
Collection переделал на List.

2022-12-21 06:13 UTC, Popsinator commented on server/src/main/java/ru/practicum/shareit/item/ItemService.java
> +    //Collection<Item> findAllItem();
Переделал во всех сервисах, удалил неиспользуемые импорты.

2022-12-21 06:24 UTC, Popsinator commented on server/src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +        List<ItemRequest> requestList = requestReporistory.findAllByRequester_IdNot(userId, PageRequest.of(start, size, Sort.by("created"))).stream().collect(Collectors.toList());
Посмотрел по всему коду, и везде сделал переносы, чтобы удобнее было.
Спасибо.

2022-12-21 06:42 UTC, Popsinator commented on server/src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>          return repository.findUserByIdEquals(userId);
Понял, красивая запись получилась, так еще не делал, спасибо.

Перешел в случае с user на option, поправил везде код и тесты.

2022-12-21 07:16 UTC, Popsinator commented on server/src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +    private final ItemRequestReporistory requestReporistory;
Понял, ничего страшного.

2022-12-21 07:55 UTC, Popsinator commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            throw new InternalServerErrorException("Отсутствует заголовок 'X-Sharer-User-Id'");
Понял, переделал это во всех сервисах.
Вынес подобные проверки в контроллеры.
Спасибо.

2022-12-21 07:56 UTC, Popsinator commented on server/src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +            throw new BadRequestException("Некорректные параметры пагинации.");
Да, спасибо, вынес проверку в контроллер.

2022-12-21 07:56 UTC, Popsinator commented on server/src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>          return repository.findUserByIdEquals(userId);
С optional работал в предыдущих модулях, но как-то подзабылось уже.

2022-12-21 10:57 UTC, Popsinator commented on gateway/src/main/java/ru/practicum/shareit/item/Item.java
> +public class Item {
По поводу валидации я сделал так, насколько понял:
1. Создал интерфейс для маркировки групп валидации.
2. И прошелся по всем классам и сделал валидации, там где посчитал необходимым.
3. Исправил нейминг, чтобы стало понятным где dto.

2022-12-21 10:57 UTC, Popsinator commented on gateway/src/main/java/ru/practicum/shareit/user/User.java
> +public class User {
Сделал по аналогии с комментарием выше.

2022-12-21 10:58 UTC, Popsinator commented on gateway/src/main/java/ru/practicum/shareit/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
Классы исключений убрал совсем.

2022-12-21 11:35 UTC, FanaticFiz commented on gateway/src/main/java/ru/practicum/shareit/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
Видел твоё сообщение в почте, всё правильно сделал что нашелся как отписаться... 
Я тут слежу за изменениями.

2022-12-21 11:59 UTC, Popsinator commented on gateway/src/main/java/ru/practicum/shareit/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
Понял, спасибо большое.
Просто переживал, думаю переделаю неправильное на неправильное, и времени тоже уже нет совсем, вот и решил написать.

2022-12-21 18:56 UTC, FanaticFiz approved these changes

2022-12-21 18:56 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public void checkPagination(String from, String size) {
Если в методы ты собираешься бросать ексепшн то я рекомендую называть его соответствующе: `throwIfPaginationNotValid` например.

2022-12-21 18:56 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (!Objects.equals(itemRepository.findItemByIdEquals(itemId).getOwner().getId(), userId)) {
- Лучше не прятать вызовы сервисов в условия
- тут сравниваем примитивы и нагляднее через !=
- в данном случае лучше инвертировать условие, потому что ! - отрицание мало заметно и не читается

```
    public Item updateItem(Item item, int itemId, Integer userId) {
        int ownerId = itemRepository.findItemByIdEquals(itemId).getOwner().getId();
        if (ownerId != userId) {
            throw new NotFoundException("Некорректный владелец item в заголовке 'X-Sharer-User-Id'");
        }

        Item itemInStorage = getItem(itemId, userId);
        Item itemUpdate = ItemMapper.toDtoItem(ItemMapper.toItemDto(item), itemInStorage);
        itemUpdate.setId(itemId);

        return itemRepository.save(itemUpdate);
    }
```

2022-12-21 18:56 UTC, FanaticFiz commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        item.setOwner(userRepository.findUserByIdEquals(userId).get());
Просто накину пример.

```
        User user = userRepository.findUserByIdEquals(userId)
                                  .orElseThrow(() -> new NotFoundException("Not found user: " + userId));
```

2022-12-27 09:05 UTC, merged